name: black formatting
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  black-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: psf/black@stable